<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Version>1.0.0</Version>
    <Authors>Aigiz Iskuzhin</Authors>
    <Product>School21Net</Product>
    <Copyright>Copyright © 2026 Aigiz Iskuzhin</Copyright>
    <PackageProjectUrl>https://github.com/ai-iskuzhin/School21Net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ai-iskuzhin/School21Net</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReleaseNotes>See https://github.com/ai-iskuzhin/School21Net/blob/main/CHANGELOG.md</PackageReleaseNotes>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>
</Project>
